Food-Waste-Optimization/Food-Waste-Optimization

branching-practices.md
Added branching practices file.
=> Branching doc

src/index.py, src/services/analysis.py, tasks.py
Data taken from "Kopio_Kumpula_asiakasdataa" and "Tuntikohtainen asiakasmäärä". 
These need to be downloaded for the model to work. 
The model can be called to make predictions by other modules.
=> Create data stub and simple regression model

Dokumentaatio/commit_practices.md, Dokumentaatio/programming_practices.md
The branch contains documents for commit and programming practices.
=> Documents mari

.github/workflows/main.yml
This is untested, because it needs to run on changes to main.
We also need unit tests in place.
=> Initial Github actions

.github/workflows/publish-docker-image.yml
This is a general test and probably will not work
=> Create publish-docker-image.yml to publish docker to docker hub

.github/workflows/publish-docker-image.yml
Reduces security with commented "Generate artifact attestation"
=> Update publish-docker-image.yml to get it to initially run

Dockerfile, docker-compose.yaml, src/index.py
=> Update docker file - Hardcore ports

src/services/analysis.py, src/services/linear_regression.py
This will allow easier development of the model. It will encapsulate the model itself from the app.
=> Change the service structure to use the ml models.

src/routers/data_router.py, src/services/formatting.py, src/templates/data.html
Modified files:
formatting.py
data_router.py
data.html
=> Created new buttons and onClick-functions to update chart view

.github/workflows/tests.yml, poetry.lock, pyproject.toml, src/tests/test_app.py, src/tests/test_dummy.py
Need to merge to test the test.
=> 48 create initial tests

Documentation/programming_practices.md
=> Fix typos in programming_practices.md

src/routers/data_router.py, src/templates/data.html
Modified files: data_router.py, data.html
=> Connecting example_model() to data template

Dockerfile, poetry.lock, pyproject.toml, src/config.py, src/index.py, src/routers/data_router.py, src/services/analysis.py
PLS TEST WELL BEFORE MERGE :)
Modified files:
modified:   Dockerfile
modified:   poetry.lock
modified:   pyproject.toml
modified:   src/config.py
modified:   src/index.py
modified:   src/routers/data_router.py
modified:   src/services/analysis.py
-Had to go through poetry.lock and pyproject.toml - for some reason poetry wasn't able to start or install anything
-Created new files with same dependencies, but some versions were automatically upgraded in the installation to match python 3.9
-Before testing do poetry install and/or poetry update
-If there are problems with dotenv, install plugin (may not be installed automatically)
poetry self add poetry-plugin-dotenv
-Modified the start command in Dockerfile to match the ones in config.py. 
-Changed some old routes that caused errors
-Cleaned …
=> Fixing config, dependencies and imports

src/index.py
Fix typo in all address interface.
=> Fix 0.0.0. -> 0.0.0.0

README.md
Update documents to current development status
=> Doc update to current

src/index.py, src/routers/data_router.py, src/services/analysis.py, src/services/linear_regression.py, src/services/neural_network.py
I have changed wrong import paths
=> Fixing wrong imports

.gitignore
Additional directories for .gitignore
=> Update more directories to .gitignore

src/app/routes.py, src/frontend/src/components/GuestView.jsx, src/frontend/src/services/requestservice.jsx
Chart for occupancy data. Doesn't show occupancy before buttons are pushed, but in my opinion could be merged to prevent diverging too much from other commits.
-Added new route to routes.py to fetch data
-Added new get-request to requestservice
-Modified the GuestView.jsx to format and display data when buttons are pushed.
=> Improving chart for GuestView.jsx

tasks.py
Add one letter to tasks.py. Yes, really.
=> Add one letter

src/frontend/src/App.jsx
An important path was excluded from App.jsx frontend
Please do not remove this line on future commits.
=> Add React View component to /fwowebserver path

src/app/routes.py
Add response headers to send full content
=> Add header response to routes

src/frontend/src/components/GuestView.jsx
Improving onclick-functions and adding button for Saturday.
=> Editing buttons and adding Saturday

src/app/routes.py, src/frontend/src/App.jsx, src/frontend/src/components/BiowasteforGuests.jsx, src/frontend/src/components/GuestView.jsx, src/frontend/src/components/MainView.jsx, src/frontend/src/components/OccupancyforGuests.jsx, src/frontend/src/services/requestservice.jsx
-Divided GuestViewjsx into 2 new components and edited chart imports to avoid conflicts
-Fetched data through requestservice and routes.py
-Edited data in routes.py to better fit into json-format and frontend demands
=> Refactor guestview and fetch data

.github/workflows/tests.yml, src/data/basic_mvp_data/README.md, src/tests/test_app.py
Work with GHA to enable environment variables and secrets for test runs. Might be useful for other parts of deployment pipeline as well.
=> Missing dummy datafiles

src/app/routes.py, src/repositories/data_repository.py, src/repositories/db_repository.py, src/services/model_service.py
Stylistic modifications for coding standard only.
We seem to have many long lines in data headers - should come up with a real fix in stead of splitting to separate lines.
Also disabling pylint warning for W0718 in many places (individually for later enhancement). The real fix is to define better the Exceptions when we get there.
=> Fix whitespace and line length issues. 

src/app/app.py, src/app/db.py, src/app/index.py, src/app/routes.py, src/config.py
=> Add docstrings

Documentation/megasense_server.md
I wrote a documentation for using megasense-server
=> Add megasense documentation

.github/workflows/deploy.yml
Redo the pipeline:
* Enable choosing of release to build
* Model after original pipeline
=> Update Github Actions release pipeline

src/frontend/src/components/BiowasteforGuests.jsx, src/frontend/src/components/Menu.jsx, src/frontend/src/components/MenuChart.jsx, src/frontend/src/components/OccupancyforGuests.jsx
- Made changes to routes - now it works at least locally on production mode
- Refactored the code on views with charts
=> Updating routes on menu, restructuring chart pages to improve code
